### ISSUE TITLE
Error when using String.prototype.padEnd()

### ISSUE THREAD

**Issue by jorgegonzalez** [dustinspecker/eslint-plugin-no-use-extend-native#113]
`"Hello, world!".padEnd(15, " ");` throws an error when this rule is used.

**Comment by jorgegonzalez** [comment]
@dustinspecker thank you for fixing so fast!

**Comment by dustinspecker** [comment]
Looks like you saw this already. I just published a new version of `is-proto-prop`, so you should be able to just reinstall `xo` then `String#padEnd` should work.

**Comment by jorgegonzalez** [comment]
You have to bump it up here to get it fixed in xo.

dustinspecker/eslint-plugin-no-use-extend-native/pull/114
