### ISSUE TITLE
Replace `rulesConfig` with a config

### ISSUE THREAD

**Issue by brettz9** [dustinspecker/eslint-plugin-no-use-extend-native#125]
Per https://eslint.org/docs/2.0.0/user-guide/migrating-to-2.0.0 , `rulesConfig` has been long abandoned, so per the docs the rule doesn't get applied when merely adding the plugin.

You can make it easier on users, however, by instead adding `configs` along with some config like "recommended" (as is common) or perhaps repeat the name "no-use-extend-native". Then just add `rules` with the rule and `plugins` with your plug-in. Then users will be able to just use `extends: ["plugin:no-use-extend-native/recommended"]` and not have to add the rule manually or add to their own `plugins`.

**Comment by dustinspecker** [comment]
Oo, thanks for bringing this up! I'll try to get this added in the next couple of days. Also happy to accept a pull request for this!
