### ISSUE TITLE
Error when using `TypedArray.of()` and `TypedArray.from()`

### ISSUE THREAD

**Issue by macarie** [dustinspecker/eslint-plugin-no-use-extend-native#126]
Using [`TypedArray.of()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/of) and [`TypedArray.from()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from) is giving me an error when using [XO](https://github.com/xojs/xo).

**Comment by dustinspecker** [comment]
https://github.com/dustinspecker/obj-props/pull/3 Taken care of over here. Please feel free to reopen if the issue still happens.
