### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [dustinspecker/eslint-plugin-no-use-extend-native#133]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by silverwind** [comment]
It works in eslint 8, but eslint 9 support would be nice too 😆.

**Comment by dustinspecker** [comment]
This looks to be working to me in eslint 8. Please let me know if you experience otherwise.
