### ISSUE TITLE
Support Flat config 

### ISSUE THREAD

**Issue by brettz9** [dustinspecker/eslint-plugin-no-use-extend-native#136]
It'd be great if you could support ESLint's flat config:

1. https://eslint.org/docs/latest/use/configure/configuration-files-new
1. https://eslint.org/blog/2022/08/new-config-system-part-1/
1. https://eslint.org/blog/2022/08/new-config-system-part-2/
1. https://eslint.org/docs/latest/use/configure/migration-guide

**Comment by silverwind** [comment]
@dustinspecker any chance this is happening?

**Comment by dustinspecker** [comment]
To my understanding, this is supported in the latest v0.6.0 release of this plugin.

Please let me know if something isn't working as expected. At this point, I've been out of the Node.js and ESLint community for years, so there's a very good chance I overlooked something.
