### ISSUE TITLE
`index.js` file is missing

### ISSUE THREAD

**Issue by SamVerschueren** [dustinspecker/eslint-plugin-no-use-extend-native#50]
You just released a new version but the `index.js` file is missing on npm. You might read this https://github.com/SamVerschueren/npm-publish-index-test.

Could you republish with an older version of npm?

**Comment by dustinspecker** [comment]
Wow, thank you for bringing this up! I just released 0.3.6.

That is a crazy bad bug.

**Comment by SamVerschueren** [comment]
They have a fix, they know what it is but no patch yet. Brought it again up to their attention that this really is something that should be fixed rather sooner then later https://github.com/npm/npm/issues/5082

Thanks for the quick fix

**Comment by dustinspecker** [comment]
Just a sec, looks like `rules` didn't get publish.
