### ISSUE TITLE
Difference from no-extend-native unclear

### ISSUE THREAD

**Issue by niedzielski** [dustinspecker/eslint-plugin-no-use-extend-native#55]
Hello! Some documentation to clarify how this plugin differs from no-extend-native[0] would be most welcome! Thank you!

[0] http://eslint.org/docs/rules/no-extend-native

**Comment by dustinspecker** [comment]
Hey. Thank you for bringing this up.

ESLint's `no-extend-native` checks that code is not **modifying** a prototype.

`no-use-extend-native` checks that code is not **using** a a non-native prototype.

These two rules pair well together, but it's not a this rule vs. that rule thing. I'm definitely open to making this clearer in the documentation. I'm open to a PR if you or others have suggestions.

Thanks again!
