### ISSUE TITLE
False positive Object.entries

### ISSUE THREAD

**Issue by gajus** [dustinspecker/eslint-plugin-no-use-extend-native#93]
I have checked this one twice after my [`Object.assing hiccup`](https://github.com/dustinspecker/eslint-plugin-no-use-extend-native/issues/91).

[`Object.entries`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) is giving me a warning.

Is this because this functionality is still experimental?

**Comment by dustinspecker** [comment]
Thanks for reporting this! This is fixed in a dependency (https://github.com/dustinspecker/obj-props/commit/fdcd889494d83bb5e7de51d5a2e58c835d79cdfa). Just needed to regenerate the list in Node 7+. I just published it.

Just reinstall `eslint-plugin-no-use-extend` and please try again.

Thank you!

**Comment by gajus** [comment]
Thank you
