### ISSUE TITLE
Support Object.entries

### ISSUE THREAD

**Issue by dvdln** [dustinspecker/eslint-plugin-no-use-extend-native#94]
Using `Object.entries` produces an error:

```
Avoid using extended native objects (no-use-extend-native/no-use-extend-native)
```

It's a native method in Node 7+. And on track for ES2017, I believe.

**Comment by dustinspecker** [comment]
Thanks for reporting this.

Did you install it more than a week ago (or shrinkwrap/lock it)? Can you try reinstalling `eslint-plugin-no-use-extend-native` please? It had a dependency update a week ago that should add support for `Object.entries`.

See more in #93.

**Comment by dvdln** [comment]
That was the problem, it's working for me now. Thank you :)
